/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "conta.h"

bool_t
xdr_Input (XDR *xdrs, Input *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->direttorio, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->soglia))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_OutputFileScan (XDR *xdrs, OutputFileScan *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->caratteri))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->parole))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->linee))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->codiceErrore))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->caratteri);
			IXDR_PUT_LONG(buf, objp->parole);
			IXDR_PUT_LONG(buf, objp->linee);
			IXDR_PUT_LONG(buf, objp->codiceErrore);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->caratteri))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->parole))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->linee))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->codiceErrore))
				 return FALSE;
		} else {
			objp->caratteri = IXDR_GET_LONG(buf);
			objp->parole = IXDR_GET_LONG(buf);
			objp->linee = IXDR_GET_LONG(buf);
			objp->codiceErrore = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->caratteri))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->parole))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->linee))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->codiceErrore))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_FileName (XDR *xdrs, FileName *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->name, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_OutputDirScan (XDR *xdrs, OutputDirScan *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->nb_files))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->files, 8,
		sizeof (FileName), (xdrproc_t) xdr_FileName))
		 return FALSE;
	return TRUE;
}
