/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _OPFILE_X_H_RPCGEN
#define _OPFILE_X_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define N 10
#define K 7
#define MAX_STRING 20

struct AggStanza {
	char nomeStanza[MAX_STRING];
	char tipo;
};
typedef struct AggStanza AggStanza;

struct Utente {
	char nome[MAX_STRING];
};
typedef struct Utente Utente;

struct Stanza {
	char nomeStanza[MAX_STRING];
	char tipo;
	Utente utente[K];
};
typedef struct Stanza Stanza;

struct ListaStanze {
	int ris;
	Stanza elenco[N];
};
typedef struct ListaStanze ListaStanze;

struct AggUtente {
	char nomeStanza[MAX_STRING];
	char nomeUtente[MAX_STRING];
};
typedef struct AggUtente AggUtente;

#define OPFILEPROG 0x20000016
#define OPFILEVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define AGGIUNGI_STANZA 1
extern  int * aggiungi_stanza_1(AggStanza *, CLIENT *);
extern  int * aggiungi_stanza_1_svc(AggStanza *, struct svc_req *);
#define ELIMINA_UTENTE 2
extern  ListaStanze * elimina_utente_1(char **, CLIENT *);
extern  ListaStanze * elimina_utente_1_svc(char **, struct svc_req *);
#define AGGIUNGI_UTENTE 3
extern  int * aggiungi_utente_1(AggUtente *, CLIENT *);
extern  int * aggiungi_utente_1_svc(AggUtente *, struct svc_req *);
#define ELIMINA_STANZA 4
extern  int * elimina_stanza_1(char **, CLIENT *);
extern  int * elimina_stanza_1_svc(char **, struct svc_req *);
#define VISUALIZZA_UTENTE 5
extern  ListaStanze * visualizza_utente_1(char **, CLIENT *);
extern  ListaStanze * visualizza_utente_1_svc(char **, struct svc_req *);
extern int opfileprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define AGGIUNGI_STANZA 1
extern  int * aggiungi_stanza_1();
extern  int * aggiungi_stanza_1_svc();
#define ELIMINA_UTENTE 2
extern  ListaStanze * elimina_utente_1();
extern  ListaStanze * elimina_utente_1_svc();
#define AGGIUNGI_UTENTE 3
extern  int * aggiungi_utente_1();
extern  int * aggiungi_utente_1_svc();
#define ELIMINA_STANZA 4
extern  int * elimina_stanza_1();
extern  int * elimina_stanza_1_svc();
#define VISUALIZZA_UTENTE 5
extern  ListaStanze * visualizza_utente_1();
extern  ListaStanze * visualizza_utente_1_svc();
extern int opfileprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_AggStanza (XDR *, AggStanza*);
extern  bool_t xdr_Utente (XDR *, Utente*);
extern  bool_t xdr_Stanza (XDR *, Stanza*);
extern  bool_t xdr_ListaStanze (XDR *, ListaStanze*);
extern  bool_t xdr_AggUtente (XDR *, AggUtente*);

#else /* K&R C */
extern bool_t xdr_AggStanza ();
extern bool_t xdr_Utente ();
extern bool_t xdr_Stanza ();
extern bool_t xdr_ListaStanze ();
extern bool_t xdr_AggUtente ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_OPFILE_X_H_RPCGEN */
